### ISSUE TITLE
SVG not generated

### ISSUE THREAD

**Issue by uolpatrickward** [dalcib/material-icons-subset#1]
Not sure if this is a limitation of the webfont npm package but I (perhaps naively) expected that setting:
`"formats": ["svg", "ttf"],`
would also output the SVG files. 
Am I misken?
Full config:
```
{
    "formats": ["svg", "ttf", "eot"],
    "fontName": "uol-md-subset",
    "fontFile": "materialicons-uol-subset",
    "dest": "./fonts",
    "icons": [
      "camera",
      "menu",
      "account-outline",
      "tune",
    ]
  }
```

**Comment by dalcib** [comment]
Thank you. 
There was a bug for other formats than `ttf`.
It is working now (v0.5.0).

**Comment by uolpatrickward** [comment]
Thanks so much for the quick response and fix. Working perfectly now.
