### ISSUE TITLE
Question regarding whether this should work like this

### ISSUE THREAD

**Issue by bliser47** [dalcib/material-icons-subset#2]
I generated my font and then tried using it inside `<i class="material-icons">phone</i>` using the https://fonts.googleapis.com/icon?family=Material+Icons but pull the subsetted font. 
Is this expected to work?

Currently it just shows the word phone and doesn't change to the phone icon.

**Comment by dalcib** [comment]
You need more css rules to makes it work.
You can see an example here: https://github.com/itgalaxy/webfont/blob/master/demo/webfont.html
If you want to generate the css automatically you can try to use the [webfont](https://github.com/itgalaxy/webfont) directly.
