### ISSUE TITLE
Getting Files glob patterns issue

### ISSUE THREAD

**Issue by VenkatRamana-xpo** [dalcib/material-icons-subset#5]
Hello, 

  While trying to convert icon subsets, I'm getting `Files glob patterns specified did not match any files` issue. When I debug the code, have found out that file paths which generated are causing it. 
  
 For the reference this is how file path returns
` 'D:\\Javascript_workspace\\material-icons-subset-master\\material-icons-subset-master\\node_modules\\@mdi\\svg\\svg\\cancel.svg'`
I have tried couple of ways to fix, one of them is if I replace all `\\ ` with `/` forward slash, It works fine and generated font files.

Does anyone face this issue?

**Comment by A-tG** [comment]
same
